repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
        additional_dependencies:
          - "alembic>=1.15.1"
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.2'
    hooks:
    -   id: flake8
        exclude: settings.py
        additional_dependencies:
          - "flake8-print==5.0.0"
          - "flake8-variables-names==0.0.6"
          - "flake8-tidy-imports==4.11.0"
-   repo: https://github.com/pycqa/isort
    rev: '6.0.1'
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: '25.1.0'
    hooks:
      - id: black